# Used dataset
https://www.kaggle.com/phylake1337/fire-dataset

In [70]:
import sys
!conda install --yes --prefix {sys.prefix} tensorflow
!{sys.executable} -m pip install tqdm

Solving environment: ...working... done

# All requested packages already installed.



In [71]:
import tensorflow as tf
import numpy as np
import os
from tqdm import tqdm
from tensorflow.keras.datasets import cifar100
from tensorflow.keras.models import Model
from tensorflow.keras.layers import InputLayer, UpSampling2D,  Conv2D, Dense
from tensorflow.keras.optimizers import Adam
import skimage as sk
from skimage.color import rgb2lab, lab2rgb
from matplotlib import pyplot as plt

In [164]:
class Encoder(Model):
    def __init__(self):
        super(Encoder, self).__init__(name='encoder')

        self.layer_1 = InputLayer((224, 224, 3))
        self.layer_2 = Conv2D(224, (3, 3), activation='relu', padding='same', strides=(2, 2))
        self.layer_3 = Conv2D(224, (3, 3), activation='relu', padding='same')
        self.layer_4 = Conv2D(112, (3, 3), activation='relu', padding='same', strides=(2, 2))
        self.layer_5 = Conv2D(112, (3, 3), activation='relu', padding='same')
        self.layer_6 = Conv2D(55, (3, 3), activation='relu', padding='same', strides=(2, 2))
        self.layer_7 = Conv2D(55, (3, 3), activation='relu', padding='same')
        self.layer_8 = Conv2D(28, (3, 3), activation='relu', padding='same', strides=(2, 2))
        self.layer_9 = Conv2D(28, (3, 3), activation='relu', padding='same')

    def call(self, inputs):
        x = self.layer_1(inputs)
        x = self.layer_2(x)
        x = self.layer_3(x)
        x = self.layer_4(x)
        x = self.layer_5(x)
        x = self.layer_6(x)
        x = self.layer_7(x)
        x = self.layer_8(x)
        x = self.layer_9(x)
        return x


In [165]:
class Decoder(Model):
    def __init__(self):
        super(Decoder, self).__init__(name='decoder')

        self.layer_1 = Conv2D(28, (3, 3), activation='relu', padding='same')
        self.layer_2 = UpSampling2D((2, 2))
        self.layer_3 = Conv2D(55, (3, 3), activation='relu', padding='same')
        self.layer_4 = UpSampling2D((2, 2))
        self.layer_5 = Conv2D(112, (3, 3), activation='relu', padding='same')
        self.layer_6 = UpSampling2D((2, 2))
        self.layer_7 = Conv2D(224, (3, 3), activation='relu', padding='same')
        self.layer_8 = Conv2D(224, (3, 3), activation='tanh', padding='same')

    def call(self, inputs):
        x = self.layer_1(inputs)
        x = self.layer_2(x)
        x = self.layer_3(x)
        x = self.layer_4(x)
        x = self.layer_5(x)
        x = self.layer_6(x)
        x = self.layer_7(x)
        x = self.layer_8(x)
        return x

In [161]:
class Autoencoder(Model):
    def __init__(self):
        super(Autoencoder, self).__init__(name='autoencoder')

        self.encoder = Encoder()
        self.decoder = Decoder()

    def call(self, inputs):
        encoded = self.encoder(inputs)
        decoded = self.decoder(encoded)
        return decoded

In [42]:
def plot_images(color, grayscale):
    plt.figure(figsize=(15,15))
    plt.subplot(1,3,1)
    plt.title('Color Image', color = 'green', fontsize = 20)
    plt.imshow(color)
    plt.subplot(1,3,2)
    plt.title('Grayscale Image ', color = 'black', fontsize = 20)
    plt.imshow(grayscale, cmap=plt.cm.gray)
   
    plt.show()

In [82]:
# Load and prepare data
SIZE = 224
color_img = []
path = './fire_images'
files = os.listdir(path)
print(len(files))
color_img = []
gray_img = []

for f in tqdm(files):
    img = plt.imread(path + '/' + f, format='jpg')
    img = sk.transform.resize(img, (SIZE, SIZE, 3))
    img = sk.img_as_float32(img)
    color_img.append(img)
    imgg = img.copy()
    for i in range(len(imgg)):
        for j in range(len(imgg)):
            num3 = np.mean(imgg[i][j])
            imgg[i][j] = np.array([num3 for _ in range(3)])
    gray_img.append(imgg)
#     plot_images(color_img[-1], gray_img[-1])
    
    

753








  0%|                                                                                          | 0/473 [00:00<?, ?it/s]

fire.352.png








  0%|▏                                                                                 | 1/473 [00:00<06:59,  1.12it/s]

fire.353.png








  0%|▎                                                                                 | 2/473 [00:01<06:57,  1.13it/s]

fire.355.png








  1%|▌                                                                                 | 3/473 [00:02<07:06,  1.10it/s]

fire.356.png








  1%|▋                                                                                 | 4/473 [00:03<06:59,  1.12it/s]

fire.357.png








  1%|▊                                                                                 | 5/473 [00:06<11:36,  1.49s/it]

fire.358.png








  1%|█                                                                                 | 6/473 [00:07<10:13,  1.31s/it]

fire.359.png








  1%|█▏                                                                                | 7/473 [00:08<09:24,  1.21s/it]

fire.36.png








  2%|█▍                                                                                | 8/473 [00:09<08:38,  1.12s/it]

fire.360.png








  2%|█▌                                                                                | 9/473 [00:10<08:05,  1.05s/it]

fire.361.png








  2%|█▋                                                                               | 10/473 [00:11<08:09,  1.06s/it]

fire.362.png








  2%|█▉                                                                               | 11/473 [00:12<07:54,  1.03s/it]

fire.363.png








  3%|██                                                                               | 12/473 [00:13<07:33,  1.02it/s]

fire.364.png








  3%|██▏                                                                              | 13/473 [00:13<07:19,  1.05it/s]

fire.365.png








  3%|██▍                                                                              | 14/473 [00:14<07:11,  1.06it/s]

fire.366.png








  3%|██▌                                                                              | 15/473 [00:15<06:52,  1.11it/s]

fire.367.png








  3%|██▋                                                                              | 16/473 [00:16<06:52,  1.11it/s]

fire.368.png








  4%|██▉                                                                              | 17/473 [00:17<06:54,  1.10it/s]

fire.369.png








  4%|███                                                                              | 18/473 [00:18<07:54,  1.04s/it]

fire.37.png








  4%|███▎                                                                             | 19/473 [00:19<07:51,  1.04s/it]

fire.370.png








  4%|███▍                                                                             | 20/473 [00:20<07:27,  1.01it/s]

fire.371.png








  4%|███▌                                                                             | 21/473 [00:21<07:08,  1.05it/s]

fire.372.png








  5%|███▊                                                                             | 22/473 [00:22<07:02,  1.07it/s]

fire.373.png








  5%|███▉                                                                             | 23/473 [00:23<06:55,  1.08it/s]

fire.374.png








  5%|████                                                                             | 24/473 [00:24<06:48,  1.10it/s]

fire.375.png








  5%|████▎                                                                            | 25/473 [00:25<06:46,  1.10it/s]

fire.376.png








  5%|████▍                                                                            | 26/473 [00:26<06:38,  1.12it/s]

fire.377.png








  6%|████▌                                                                            | 27/473 [00:26<06:34,  1.13it/s]

fire.378.png








  6%|████▊                                                                            | 28/473 [00:27<06:35,  1.13it/s]

fire.379.png








  6%|████▉                                                                            | 29/473 [00:28<07:01,  1.05it/s]

fire.38.png








  6%|█████▏                                                                           | 30/473 [00:29<06:52,  1.07it/s]

fire.380.png








  7%|█████▎                                                                           | 31/473 [00:30<06:53,  1.07it/s]

fire.381.png








  7%|█████▍                                                                           | 32/473 [00:31<07:15,  1.01it/s]

fire.382.png








  7%|█████▋                                                                           | 33/473 [00:32<07:00,  1.05it/s]

fire.383.png








  7%|█████▊                                                                           | 34/473 [00:33<06:54,  1.06it/s]

fire.384.png








  7%|█████▉                                                                           | 35/473 [00:34<06:48,  1.07it/s]

fire.385.png








  8%|██████▏                                                                          | 36/473 [00:35<06:42,  1.09it/s]

fire.386.png








  8%|██████▎                                                                          | 37/473 [00:36<06:37,  1.10it/s]

fire.387.png








  8%|██████▌                                                                          | 38/473 [00:37<06:26,  1.13it/s]

fire.388.png








  8%|██████▋                                                                          | 39/473 [00:38<06:23,  1.13it/s]

fire.389.png








  8%|██████▊                                                                          | 40/473 [00:38<06:22,  1.13it/s]

fire.39.png








  9%|███████                                                                          | 41/473 [00:39<06:22,  1.13it/s]

fire.390.png








  9%|███████▏                                                                         | 42/473 [00:40<06:25,  1.12it/s]

fire.391.png








  9%|███████▎                                                                         | 43/473 [00:41<06:23,  1.12it/s]

fire.392.png








  9%|███████▌                                                                         | 44/473 [00:42<06:24,  1.11it/s]

fire.393.png








 10%|███████▋                                                                         | 45/473 [00:51<23:15,  3.26s/it]

fire.394.png








 10%|███████▉                                                                         | 46/473 [00:52<18:08,  2.55s/it]

fire.395.png








 10%|████████                                                                         | 47/473 [00:53<14:33,  2.05s/it]

fire.396.png








 10%|████████▏                                                                        | 48/473 [00:53<12:02,  1.70s/it]

fire.397.png








 10%|████████▍                                                                        | 49/473 [00:54<10:21,  1.47s/it]

fire.398.png








 11%|████████▌                                                                        | 50/473 [00:55<09:06,  1.29s/it]

fire.399.png








 11%|████████▋                                                                        | 51/473 [00:56<08:18,  1.18s/it]

fire.4.png








 11%|████████▉                                                                        | 52/473 [00:57<07:37,  1.09s/it]

fire.40.png








 11%|█████████                                                                        | 53/473 [00:58<07:09,  1.02s/it]

fire.400.png








 11%|█████████▏                                                                       | 54/473 [00:59<06:56,  1.01it/s]

fire.401.png








 12%|█████████▍                                                                       | 55/473 [01:00<06:41,  1.04it/s]

fire.402.png








 12%|█████████▌                                                                       | 56/473 [01:02<08:42,  1.25s/it]

fire.403.png








 12%|█████████▊                                                                       | 57/473 [01:03<08:03,  1.16s/it]

fire.404.png








 12%|█████████▉                                                                       | 58/473 [01:04<09:10,  1.33s/it]

fire.405.png








 12%|██████████                                                                       | 59/473 [01:10<17:14,  2.50s/it]

fire.406.png








 13%|██████████▎                                                                      | 60/473 [01:10<13:54,  2.02s/it]

fire.407.png








 13%|██████████▍                                                                      | 61/473 [01:11<11:24,  1.66s/it]

fire.408.png








 13%|██████████▌                                                                      | 62/473 [01:12<09:46,  1.43s/it]

fire.409.png








 13%|██████████▊                                                                      | 63/473 [01:13<08:33,  1.25s/it]

fire.41.png








 14%|██████████▉                                                                      | 64/473 [01:14<07:46,  1.14s/it]

fire.410.png








 14%|███████████▏                                                                     | 65/473 [01:15<07:14,  1.07s/it]

fire.411.png








 14%|███████████▎                                                                     | 66/473 [01:16<06:51,  1.01s/it]

fire.412.png








 14%|███████████▍                                                                     | 67/473 [01:17<06:36,  1.02it/s]

fire.413.png








 14%|███████████▋                                                                     | 68/473 [01:17<06:23,  1.06it/s]

fire.414.png








 15%|███████████▊                                                                     | 69/473 [01:18<06:15,  1.07it/s]

fire.415.png








 15%|███████████▉                                                                     | 70/473 [01:19<06:12,  1.08it/s]

fire.416.png








 15%|████████████▏                                                                    | 71/473 [01:25<15:43,  2.35s/it]

fire.417.png








 15%|████████████▎                                                                    | 72/473 [01:26<12:46,  1.91s/it]

fire.418.png








 15%|████████████▌                                                                    | 73/473 [01:27<10:52,  1.63s/it]

fire.419.png








 16%|████████████▋                                                                    | 74/473 [01:28<10:05,  1.52s/it]

fire.42.png








 16%|████████████▊                                                                    | 75/473 [01:29<08:48,  1.33s/it]

fire.420.png








 16%|█████████████                                                                    | 76/473 [01:31<09:22,  1.42s/it]

fire.421.png








 16%|█████████████▏                                                                   | 77/473 [01:32<08:58,  1.36s/it]

fire.422.png








 16%|█████████████▎                                                                   | 78/473 [01:33<07:59,  1.21s/it]

fire.423.png








 17%|█████████████▌                                                                   | 79/473 [01:34<07:23,  1.13s/it]

fire.424.png








 17%|█████████████▋                                                                   | 80/473 [01:34<06:58,  1.06s/it]

fire.425.png








 17%|█████████████▊                                                                   | 81/473 [01:35<06:37,  1.02s/it]

fire.426.png








 17%|██████████████                                                                   | 82/473 [01:36<06:23,  1.02it/s]

fire.427.png








 18%|██████████████▏                                                                  | 83/473 [01:38<08:16,  1.27s/it]

fire.428.png








 18%|██████████████▍                                                                  | 84/473 [01:39<07:46,  1.20s/it]

fire.429.png








 18%|██████████████▌                                                                  | 85/473 [01:40<07:16,  1.12s/it]

fire.43.png








 18%|██████████████▋                                                                  | 86/473 [01:41<06:50,  1.06s/it]

fire.430.png








 18%|██████████████▉                                                                  | 87/473 [01:42<06:40,  1.04s/it]

fire.431.png








 19%|███████████████                                                                  | 88/473 [01:43<06:45,  1.05s/it]

fire.432.png








 19%|███████████████▏                                                                 | 89/473 [01:44<06:25,  1.00s/it]

fire.433.png








 19%|███████████████▍                                                                 | 90/473 [01:45<06:13,  1.03it/s]

fire.434.png








 19%|███████████████▌                                                                 | 91/473 [01:50<14:46,  2.32s/it]

fire.435.png








 19%|███████████████▊                                                                 | 92/473 [01:51<12:02,  1.90s/it]

fire.436.png








 20%|███████████████▉                                                                 | 93/473 [01:52<10:07,  1.60s/it]

fire.437.png








 20%|████████████████                                                                 | 94/473 [01:53<08:54,  1.41s/it]

fire.438.png








 20%|████████████████▎                                                                | 95/473 [01:55<09:07,  1.45s/it]

fire.439.png








 20%|████████████████▍                                                                | 96/473 [01:56<08:02,  1.28s/it]

fire.44.png








 21%|████████████████▌                                                                | 97/473 [01:57<07:13,  1.15s/it]

fire.440.png








 21%|████████████████▊                                                                | 98/473 [01:57<06:42,  1.07s/it]

fire.441.png








 21%|████████████████▉                                                                | 99/473 [02:00<10:12,  1.64s/it]

fire.442.png








 21%|████████████████▉                                                               | 100/473 [02:01<08:44,  1.41s/it]

fire.443.png








 21%|█████████████████                                                               | 101/473 [02:02<07:46,  1.25s/it]

fire.444.png








 22%|█████████████████▎                                                              | 102/473 [02:03<07:28,  1.21s/it]

fire.445.png








 22%|█████████████████▍                                                              | 103/473 [02:04<06:54,  1.12s/it]

fire.446.png








 22%|█████████████████▌                                                              | 104/473 [02:05<06:30,  1.06s/it]

fire.447.png








 22%|█████████████████▊                                                              | 105/473 [02:06<06:10,  1.01s/it]

fire.448.png








 22%|█████████████████▉                                                              | 106/473 [02:07<05:57,  1.03it/s]

fire.449.png








 23%|██████████████████                                                              | 107/473 [02:08<05:47,  1.05it/s]

fire.45.png








 23%|██████████████████▎                                                             | 108/473 [02:09<05:41,  1.07it/s]

fire.450.png








 23%|██████████████████▍                                                             | 109/473 [02:10<05:33,  1.09it/s]

fire.451.png








 23%|██████████████████▌                                                             | 110/473 [02:11<05:49,  1.04it/s]

fire.452.png








 23%|██████████████████▊                                                             | 111/473 [02:11<05:43,  1.05it/s]

fire.453.png








 24%|██████████████████▉                                                             | 112/473 [02:12<05:35,  1.08it/s]

fire.454.png








 24%|███████████████████                                                             | 113/473 [02:13<05:34,  1.08it/s]

fire.455.png








 24%|███████████████████▎                                                            | 114/473 [02:14<05:28,  1.09it/s]

fire.456.png








 24%|███████████████████▍                                                            | 115/473 [02:15<05:24,  1.10it/s]

fire.457.png








 25%|███████████████████▌                                                            | 116/473 [02:16<05:22,  1.11it/s]

fire.458.png








 25%|███████████████████▊                                                            | 117/473 [02:17<05:20,  1.11it/s]

fire.459.png








 25%|███████████████████▉                                                            | 118/473 [02:18<05:35,  1.06it/s]

fire.46.png








 25%|████████████████████▏                                                           | 119/473 [02:19<05:27,  1.08it/s]

fire.460.png








 25%|████████████████████▎                                                           | 120/473 [02:20<05:23,  1.09it/s]

fire.461.png








 26%|████████████████████▍                                                           | 121/473 [02:21<05:23,  1.09it/s]

fire.462.png








 26%|████████████████████▋                                                           | 122/473 [02:22<06:22,  1.09s/it]

fire.463.png








 26%|████████████████████▊                                                           | 123/473 [02:23<06:02,  1.03s/it]

fire.464.png








 26%|████████████████████▉                                                           | 124/473 [02:24<05:55,  1.02s/it]

fire.465.png








 26%|█████████████████████▏                                                          | 125/473 [02:25<05:40,  1.02it/s]

fire.466.png








 27%|█████████████████████▎                                                          | 126/473 [02:26<05:27,  1.06it/s]

fire.467.png








 27%|█████████████████████▍                                                          | 127/473 [02:27<05:19,  1.08it/s]

fire.468.png








 27%|█████████████████████▋                                                          | 128/473 [02:28<05:30,  1.04it/s]

fire.469.png








 27%|█████████████████████▊                                                          | 129/473 [02:33<13:24,  2.34s/it]

fire.47.png








 27%|█████████████████████▉                                                          | 130/473 [02:34<10:53,  1.91s/it]

fire.470.png








 28%|██████████████████████▏                                                         | 131/473 [02:35<09:10,  1.61s/it]

fire.471.png








 28%|██████████████████████▎                                                         | 132/473 [02:36<07:54,  1.39s/it]

fire.472.png








 28%|██████████████████████▍                                                         | 133/473 [02:37<07:01,  1.24s/it]

fire.473.png








 28%|██████████████████████▋                                                         | 134/473 [02:38<06:27,  1.14s/it]

fire.474.png








 29%|██████████████████████▊                                                         | 135/473 [02:39<05:59,  1.06s/it]

fire.475.png








 29%|███████████████████████                                                         | 136/473 [02:39<05:41,  1.01s/it]

fire.476.png








 29%|███████████████████████▏                                                        | 137/473 [02:40<05:33,  1.01it/s]

fire.477.png








 29%|███████████████████████▎                                                        | 138/473 [02:41<05:25,  1.03it/s]

fire.478.png








 29%|███████████████████████▌                                                        | 139/473 [02:42<05:19,  1.05it/s]

fire.479.png








 30%|███████████████████████▋                                                        | 140/473 [02:46<10:44,  1.94s/it]

fire.48.png








 30%|███████████████████████▊                                                        | 141/473 [02:48<09:12,  1.66s/it]

fire.480.png








 30%|████████████████████████                                                        | 142/473 [02:48<07:56,  1.44s/it]

fire.481.png








 30%|████████████████████████▏                                                       | 143/473 [02:49<07:03,  1.28s/it]

fire.482.png








 30%|████████████████████████▎                                                       | 144/473 [02:50<06:21,  1.16s/it]

fire.483.png








 31%|████████████████████████▌                                                       | 145/473 [02:51<05:54,  1.08s/it]

fire.484.png








 31%|████████████████████████▋                                                       | 146/473 [02:52<05:36,  1.03s/it]

fire.485.png








 31%|████████████████████████▊                                                       | 147/473 [02:53<05:29,  1.01s/it]

fire.486.png








 31%|█████████████████████████                                                       | 148/473 [02:54<05:21,  1.01it/s]

fire.487.png








 32%|█████████████████████████▏                                                      | 149/473 [02:55<05:09,  1.05it/s]

fire.488.png








 32%|█████████████████████████▎                                                      | 150/473 [02:59<09:46,  1.82s/it]

fire.489.png








 32%|█████████████████████████▌                                                      | 151/473 [03:00<08:18,  1.55s/it]

fire.49.png








 32%|█████████████████████████▋                                                      | 152/473 [03:00<07:14,  1.35s/it]

fire.490.png








 32%|█████████████████████████▉                                                      | 153/473 [03:01<06:28,  1.22s/it]

fire.491.png








 33%|██████████████████████████                                                      | 154/473 [03:02<06:09,  1.16s/it]

fire.492.png








 33%|██████████████████████████▏                                                     | 155/473 [03:03<05:42,  1.08s/it]

fire.493.png








 33%|██████████████████████████▍                                                     | 156/473 [03:05<06:40,  1.26s/it]

fire.494.png








 33%|██████████████████████████▌                                                     | 157/473 [03:06<06:04,  1.15s/it]

fire.495.png








 33%|██████████████████████████▋                                                     | 158/473 [03:08<08:04,  1.54s/it]

fire.496.png








 34%|██████████████████████████▉                                                     | 159/473 [03:09<07:03,  1.35s/it]

fire.497.png








 34%|███████████████████████████                                                     | 160/473 [03:10<06:19,  1.21s/it]

fire.498.png








 34%|███████████████████████████▏                                                    | 161/473 [03:11<05:46,  1.11s/it]

fire.499.png








 34%|███████████████████████████▍                                                    | 162/473 [03:12<05:25,  1.05s/it]

fire.5.png








 34%|███████████████████████████▌                                                    | 163/473 [03:13<05:09,  1.00it/s]

fire.50.png








 35%|███████████████████████████▋                                                    | 164/473 [03:14<05:07,  1.00it/s]

fire.500.png








 35%|███████████████████████████▉                                                    | 165/473 [03:15<04:56,  1.04it/s]

fire.501.png








 35%|████████████████████████████                                                    | 166/473 [03:16<04:51,  1.05it/s]

fire.502.png








 35%|████████████████████████████▏                                                   | 167/473 [03:16<04:47,  1.07it/s]

fire.503.png








 36%|████████████████████████████▍                                                   | 168/473 [03:17<04:41,  1.08it/s]

fire.504.png








 36%|████████████████████████████▌                                                   | 169/473 [03:18<04:38,  1.09it/s]

fire.505.png








 36%|████████████████████████████▊                                                   | 170/473 [03:19<04:34,  1.10it/s]

fire.506.png








 36%|████████████████████████████▉                                                   | 171/473 [03:20<04:34,  1.10it/s]

fire.507.png








 36%|█████████████████████████████                                                   | 172/473 [03:21<04:31,  1.11it/s]

fire.508.png








 37%|█████████████████████████████▎                                                  | 173/473 [03:22<04:32,  1.10it/s]

fire.509.png








 37%|█████████████████████████████▍                                                  | 174/473 [03:23<04:30,  1.11it/s]

fire.51.png








 37%|█████████████████████████████▌                                                  | 175/473 [03:24<04:34,  1.09it/s]

fire.510.png








 37%|█████████████████████████████▊                                                  | 176/473 [03:25<04:30,  1.10it/s]

fire.511.png








 37%|█████████████████████████████▉                                                  | 177/473 [03:26<04:31,  1.09it/s]

fire.512.png








 38%|██████████████████████████████                                                  | 178/473 [03:27<04:44,  1.04it/s]

fire.513.png








 38%|██████████████████████████████▎                                                 | 179/473 [03:28<04:43,  1.04it/s]

fire.514.png








 38%|██████████████████████████████▍                                                 | 180/473 [03:28<04:35,  1.06it/s]

fire.515.png








 38%|██████████████████████████████▌                                                 | 181/473 [03:29<04:37,  1.05it/s]

fire.516.png








 38%|██████████████████████████████▊                                                 | 182/473 [03:30<04:30,  1.07it/s]

fire.517.png








 39%|██████████████████████████████▉                                                 | 183/473 [03:31<04:48,  1.01it/s]

fire.518.png








 39%|███████████████████████████████                                                 | 184/473 [03:32<04:36,  1.04it/s]

fire.519.png








 39%|███████████████████████████████▎                                                | 185/473 [03:33<04:34,  1.05it/s]

fire.52.png








 39%|███████████████████████████████▍                                                | 186/473 [03:34<04:28,  1.07it/s]

fire.520.png








 40%|███████████████████████████████▋                                                | 187/473 [03:35<04:24,  1.08it/s]

fire.521.png








 40%|███████████████████████████████▊                                                | 188/473 [03:36<04:20,  1.10it/s]

fire.522.png








 40%|███████████████████████████████▉                                                | 189/473 [03:37<04:16,  1.11it/s]

fire.523.png








 40%|████████████████████████████████▏                                               | 190/473 [03:38<04:17,  1.10it/s]

fire.524.png








 40%|████████████████████████████████▎                                               | 191/473 [03:39<04:17,  1.10it/s]

fire.525.png








 41%|████████████████████████████████▍                                               | 192/473 [03:40<04:17,  1.09it/s]

fire.526.png








 41%|████████████████████████████████▋                                               | 193/473 [03:41<05:39,  1.21s/it]

fire.527.png








 41%|████████████████████████████████▊                                               | 194/473 [03:42<05:09,  1.11s/it]

fire.528.png








 41%|████████████████████████████████▉                                               | 195/473 [03:43<04:50,  1.04s/it]

fire.529.png








 41%|█████████████████████████████████▏                                              | 196/473 [03:44<04:37,  1.00s/it]

fire.53.png








 42%|█████████████████████████████████▎                                              | 197/473 [03:45<04:35,  1.00it/s]

fire.530.png








 42%|█████████████████████████████████▍                                              | 198/473 [03:46<04:25,  1.04it/s]

fire.531.png








 42%|█████████████████████████████████▋                                              | 199/473 [03:47<04:39,  1.02s/it]

fire.532.png








 42%|█████████████████████████████████▊                                              | 200/473 [03:48<04:34,  1.00s/it]

fire.533.png








 42%|█████████████████████████████████▉                                              | 201/473 [03:49<04:24,  1.03it/s]

fire.534.png








 43%|██████████████████████████████████▏                                             | 202/473 [03:50<04:16,  1.06it/s]

fire.535.png








 43%|██████████████████████████████████▎                                             | 203/473 [03:51<04:12,  1.07it/s]

fire.536.png








 43%|██████████████████████████████████▌                                             | 204/473 [03:52<04:07,  1.09it/s]

fire.537.png








 43%|██████████████████████████████████▋                                             | 205/473 [03:53<03:58,  1.12it/s]

fire.538.png








 44%|██████████████████████████████████▊                                             | 206/473 [03:54<04:45,  1.07s/it]

fire.539.png








 44%|███████████████████████████████████                                             | 207/473 [03:55<04:31,  1.02s/it]

fire.54.png








 44%|███████████████████████████████████▏                                            | 208/473 [03:56<04:19,  1.02it/s]

fire.540.png








 44%|███████████████████████████████████▎                                            | 209/473 [03:57<04:14,  1.04it/s]

fire.541.png








 44%|███████████████████████████████████▌                                            | 210/473 [03:58<04:09,  1.05it/s]

fire.542.png








 45%|███████████████████████████████████▋                                            | 211/473 [03:59<04:04,  1.07it/s]

fire.543.png








 45%|███████████████████████████████████▊                                            | 212/473 [04:00<04:05,  1.06it/s]

fire.544.png








 45%|████████████████████████████████████                                            | 213/473 [04:01<04:17,  1.01it/s]

fire.545.png








 45%|████████████████████████████████████▏                                           | 214/473 [04:02<04:07,  1.04it/s]

fire.546.png








 45%|████████████████████████████████████▎                                           | 215/473 [04:02<04:03,  1.06it/s]

fire.547.png








 46%|████████████████████████████████████▌                                           | 216/473 [04:03<04:00,  1.07it/s]

fire.548.png








 46%|████████████████████████████████████▋                                           | 217/473 [04:04<03:58,  1.07it/s]

fire.549.png








 46%|████████████████████████████████████▊                                           | 218/473 [04:06<04:29,  1.06s/it]

fire.55.png








 46%|█████████████████████████████████████                                           | 219/473 [04:06<04:14,  1.00s/it]

fire.550.png








 47%|█████████████████████████████████████▏                                          | 220/473 [04:07<04:04,  1.04it/s]

fire.551.png








 47%|█████████████████████████████████████▍                                          | 221/473 [04:08<03:58,  1.06it/s]

fire.552.png








 47%|█████████████████████████████████████▌                                          | 222/473 [04:09<03:51,  1.08it/s]

fire.553.png








 47%|█████████████████████████████████████▋                                          | 223/473 [04:10<03:43,  1.12it/s]

fire.554.png








 47%|█████████████████████████████████████▉                                          | 224/473 [04:11<03:44,  1.11it/s]

fire.555.png








 48%|██████████████████████████████████████                                          | 225/473 [04:12<03:44,  1.10it/s]

fire.556.png








 48%|██████████████████████████████████████▏                                         | 226/473 [04:20<12:54,  3.14s/it]

fire.557.png








 48%|██████████████████████████████████████▍                                         | 227/473 [04:21<10:06,  2.46s/it]

fire.558.png








 48%|██████████████████████████████████████▌                                         | 228/473 [04:24<10:24,  2.55s/it]

fire.559.png








 48%|██████████████████████████████████████▋                                         | 229/473 [04:25<08:19,  2.05s/it]

fire.56.png








 49%|██████████████████████████████████████▉                                         | 230/473 [04:25<06:47,  1.68s/it]

fire.560.png








 49%|███████████████████████████████████████                                         | 231/473 [04:26<05:47,  1.44s/it]

fire.561.png








 49%|███████████████████████████████████████▏                                        | 232/473 [04:27<05:03,  1.26s/it]

fire.562.png








 49%|███████████████████████████████████████▍                                        | 233/473 [04:28<04:32,  1.13s/it]

fire.563.png








 49%|███████████████████████████████████████▌                                        | 234/473 [04:29<04:12,  1.06s/it]

fire.564.png








 50%|███████████████████████████████████████▋                                        | 235/473 [04:34<09:22,  2.36s/it]

fire.565.png








 50%|███████████████████████████████████████▉                                        | 236/473 [04:39<11:35,  2.94s/it]

fire.566.png








 50%|████████████████████████████████████████                                        | 237/473 [04:39<09:07,  2.32s/it]

fire.567.png








 50%|████████████████████████████████████████▎                                       | 238/473 [04:41<07:39,  1.96s/it]

fire.568.png








 51%|████████████████████████████████████████▍                                       | 239/473 [04:41<06:24,  1.64s/it]

fire.569.png








 51%|████████████████████████████████████████▌                                       | 240/473 [04:42<05:31,  1.42s/it]

fire.57.png








 51%|████████████████████████████████████████▊                                       | 241/473 [04:43<04:55,  1.27s/it]

fire.570.png








 51%|████████████████████████████████████████▉                                       | 242/473 [04:44<04:26,  1.16s/it]

fire.571.png








 51%|█████████████████████████████████████████                                       | 243/473 [04:45<04:11,  1.09s/it]

fire.572.png








 52%|█████████████████████████████████████████▎                                      | 244/473 [04:46<03:58,  1.04s/it]

fire.573.png








 52%|█████████████████████████████████████████▍                                      | 245/473 [04:47<03:48,  1.00s/it]

fire.574.png








 52%|█████████████████████████████████████████▌                                      | 246/473 [04:50<06:29,  1.72s/it]

fire.575.png








 52%|█████████████████████████████████████████▊                                      | 247/473 [04:51<05:31,  1.47s/it]

fire.576.png








 52%|█████████████████████████████████████████▉                                      | 248/473 [04:53<05:46,  1.54s/it]

fire.577.png








 53%|██████████████████████████████████████████                                      | 249/473 [04:54<05:02,  1.35s/it]

fire.578.png








 53%|██████████████████████████████████████████▎                                     | 250/473 [04:55<04:32,  1.22s/it]

fire.579.png








 53%|██████████████████████████████████████████▍                                     | 251/473 [04:56<04:10,  1.13s/it]

fire.58.png








 53%|██████████████████████████████████████████▌                                     | 252/473 [04:58<05:34,  1.51s/it]

fire.580.png








 53%|██████████████████████████████████████████▊                                     | 253/473 [04:59<05:04,  1.38s/it]

fire.581.png








 54%|██████████████████████████████████████████▉                                     | 254/473 [05:00<04:31,  1.24s/it]

fire.582.png








 54%|███████████████████████████████████████████▏                                    | 255/473 [05:01<04:08,  1.14s/it]

fire.583.png








 54%|███████████████████████████████████████████▎                                    | 256/473 [05:02<03:51,  1.07s/it]

fire.584.png








 54%|███████████████████████████████████████████▍                                    | 257/473 [05:03<03:43,  1.03s/it]

fire.585.png








 55%|███████████████████████████████████████████▋                                    | 258/473 [05:04<03:33,  1.01it/s]

fire.586.png








 55%|███████████████████████████████████████████▊                                    | 259/473 [05:05<03:25,  1.04it/s]

fire.587.png








 55%|███████████████████████████████████████████▉                                    | 260/473 [05:06<03:22,  1.05it/s]

fire.588.png








 55%|████████████████████████████████████████████▏                                   | 261/473 [05:06<03:18,  1.07it/s]

fire.589.png








 55%|████████████████████████████████████████████▎                                   | 262/473 [05:07<03:14,  1.09it/s]

fire.59.png








 56%|████████████████████████████████████████████▍                                   | 263/473 [05:08<03:11,  1.10it/s]

fire.590.png








 56%|████████████████████████████████████████████▋                                   | 264/473 [05:09<03:09,  1.10it/s]

fire.591.png








 56%|████████████████████████████████████████████▊                                   | 265/473 [05:10<03:11,  1.08it/s]

fire.592.png








 56%|████████████████████████████████████████████▉                                   | 266/473 [05:11<03:13,  1.07it/s]

fire.593.png








 56%|█████████████████████████████████████████████▏                                  | 267/473 [05:12<03:12,  1.07it/s]

fire.594.png








 57%|█████████████████████████████████████████████▎                                  | 268/473 [05:13<03:08,  1.09it/s]

fire.595.png








 57%|█████████████████████████████████████████████▍                                  | 269/473 [05:14<03:09,  1.08it/s]

fire.596.png








 57%|█████████████████████████████████████████████▋                                  | 270/473 [05:15<03:42,  1.10s/it]

fire.597.png








 57%|█████████████████████████████████████████████▊                                  | 271/473 [05:16<03:31,  1.05s/it]

fire.598.png








 58%|██████████████████████████████████████████████                                  | 272/473 [05:17<03:32,  1.06s/it]

fire.599.png








 58%|██████████████████████████████████████████████▏                                 | 273/473 [05:18<03:21,  1.01s/it]

fire.6.png








 58%|██████████████████████████████████████████████▎                                 | 274/473 [05:19<03:35,  1.08s/it]

fire.60.png








 58%|██████████████████████████████████████████████▌                                 | 275/473 [05:20<03:28,  1.05s/it]

fire.600.png








 58%|██████████████████████████████████████████████▋                                 | 276/473 [05:21<03:20,  1.02s/it]

fire.601.png








 59%|██████████████████████████████████████████████▊                                 | 277/473 [05:22<03:11,  1.02it/s]

fire.602.png








 59%|███████████████████████████████████████████████                                 | 278/473 [05:23<03:07,  1.04it/s]

fire.603.png








 59%|███████████████████████████████████████████████▏                                | 279/473 [05:24<03:04,  1.05it/s]

fire.604.png








 59%|███████████████████████████████████████████████▎                                | 280/473 [05:25<03:00,  1.07it/s]

fire.605.png








 59%|███████████████████████████████████████████████▌                                | 281/473 [05:26<03:12,  1.00s/it]

fire.606.png








 60%|███████████████████████████████████████████████▋                                | 282/473 [05:27<03:05,  1.03it/s]

fire.607.png








 60%|███████████████████████████████████████████████▊                                | 283/473 [05:31<06:13,  1.97s/it]

fire.608.png








 60%|████████████████████████████████████████████████                                | 284/473 [05:32<05:12,  1.65s/it]

fire.609.png








 60%|████████████████████████████████████████████████▏                               | 285/473 [05:33<04:30,  1.44s/it]

fire.61.png








 60%|████████████████████████████████████████████████▎                               | 286/473 [05:34<03:58,  1.28s/it]

fire.610.png








 61%|████████████████████████████████████████████████▌                               | 287/473 [05:35<03:34,  1.15s/it]

fire.611.png








 61%|████████████████████████████████████████████████▋                               | 288/473 [05:36<03:18,  1.07s/it]

fire.612.png








 61%|████████████████████████████████████████████████▉                               | 289/473 [05:37<03:19,  1.09s/it]

fire.613.png








 61%|█████████████████████████████████████████████████                               | 290/473 [05:38<03:08,  1.03s/it]

fire.614.png








 62%|█████████████████████████████████████████████████▏                              | 291/473 [05:39<03:00,  1.01it/s]

fire.615.png








 62%|█████████████████████████████████████████████████▍                              | 292/473 [05:40<02:53,  1.04it/s]

fire.616.png








 62%|█████████████████████████████████████████████████▌                              | 293/473 [05:41<02:49,  1.06it/s]

fire.617.png








 62%|█████████████████████████████████████████████████▋                              | 294/473 [05:42<02:49,  1.05it/s]

fire.618.png








 62%|█████████████████████████████████████████████████▉                              | 295/473 [05:42<02:45,  1.08it/s]

fire.619.png








 63%|██████████████████████████████████████████████████                              | 296/473 [05:43<02:49,  1.05it/s]

fire.62.png








 63%|██████████████████████████████████████████████████▏                             | 297/473 [05:44<02:45,  1.06it/s]

fire.620.png








 63%|██████████████████████████████████████████████████▍                             | 298/473 [05:45<02:43,  1.07it/s]

fire.621.png








 63%|██████████████████████████████████████████████████▌                             | 299/473 [05:48<04:23,  1.51s/it]

fire.622.png








 63%|██████████████████████████████████████████████████▋                             | 300/473 [05:49<03:49,  1.33s/it]

fire.623.png








 64%|██████████████████████████████████████████████████▉                             | 301/473 [05:50<03:26,  1.20s/it]

fire.624.png








 64%|███████████████████████████████████████████████████                             | 302/473 [05:51<03:09,  1.11s/it]

fire.625.png








 64%|███████████████████████████████████████████████████▏                            | 303/473 [05:52<03:01,  1.07s/it]

fire.626.png








 64%|███████████████████████████████████████████████████▍                            | 304/473 [05:53<02:54,  1.03s/it]

fire.627.png








 64%|███████████████████████████████████████████████████▌                            | 305/473 [05:58<06:25,  2.29s/it]

fire.628.png








 65%|███████████████████████████████████████████████████▊                            | 306/473 [05:59<05:11,  1.86s/it]

fire.629.png








 65%|███████████████████████████████████████████████████▉                            | 307/473 [06:00<04:22,  1.58s/it]

fire.63.png








 65%|████████████████████████████████████████████████████                            | 308/473 [06:01<03:47,  1.38s/it]

fire.630.png








 65%|████████████████████████████████████████████████████▎                           | 309/473 [06:02<03:23,  1.24s/it]

fire.631.png








 66%|████████████████████████████████████████████████████▍                           | 310/473 [06:03<03:19,  1.23s/it]

fire.632.png








 66%|████████████████████████████████████████████████████▌                           | 311/473 [06:04<03:00,  1.11s/it]

fire.633.png








 66%|████████████████████████████████████████████████████▊                           | 312/473 [06:05<02:49,  1.05s/it]

fire.634.png








 66%|████████████████████████████████████████████████████▉                           | 313/473 [06:05<02:41,  1.01s/it]

fire.635.png








 66%|█████████████████████████████████████████████████████                           | 314/473 [06:06<02:35,  1.03it/s]

fire.636.png








 67%|█████████████████████████████████████████████████████▎                          | 315/473 [06:07<02:29,  1.06it/s]

fire.637.png








 67%|█████████████████████████████████████████████████████▍                          | 316/473 [06:08<02:32,  1.03it/s]

fire.638.png








 67%|█████████████████████████████████████████████████████▌                          | 317/473 [06:09<02:27,  1.05it/s]

fire.639.png








 67%|█████████████████████████████████████████████████████▊                          | 318/473 [06:10<02:24,  1.07it/s]

fire.64.png








 67%|█████████████████████████████████████████████████████▉                          | 319/473 [06:11<02:20,  1.09it/s]

fire.640.png








 68%|██████████████████████████████████████████████████████                          | 320/473 [06:12<02:46,  1.09s/it]

fire.641.png








 68%|██████████████████████████████████████████████████████▎                         | 321/473 [06:13<02:35,  1.02s/it]

fire.642.png








 68%|██████████████████████████████████████████████████████▍                         | 322/473 [06:14<02:27,  1.02it/s]

fire.643.png








 68%|██████████████████████████████████████████████████████▋                         | 323/473 [06:15<02:22,  1.05it/s]

fire.644.png








 68%|██████████████████████████████████████████████████████▊                         | 324/473 [06:16<02:20,  1.06it/s]

fire.645.png








 69%|██████████████████████████████████████████████████████▉                         | 325/473 [06:17<02:17,  1.08it/s]

fire.646.png








 69%|███████████████████████████████████████████████████████▏                        | 326/473 [06:18<02:14,  1.09it/s]

fire.647.png








 69%|███████████████████████████████████████████████████████▎                        | 327/473 [06:19<02:20,  1.04it/s]

fire.648.png








 69%|███████████████████████████████████████████████████████▍                        | 328/473 [06:20<02:32,  1.05s/it]

fire.649.png








 70%|███████████████████████████████████████████████████████▋                        | 329/473 [06:21<02:23,  1.00it/s]

fire.65.png








 70%|███████████████████████████████████████████████████████▊                        | 330/473 [06:22<02:17,  1.04it/s]

fire.650.png








 70%|███████████████████████████████████████████████████████▉                        | 331/473 [06:23<02:13,  1.06it/s]

fire.651.png








 70%|████████████████████████████████████████████████████████▏                       | 332/473 [06:24<02:16,  1.03it/s]

fire.652.png








 70%|████████████████████████████████████████████████████████▎                       | 333/473 [06:25<02:14,  1.04it/s]

fire.653.png








 71%|████████████████████████████████████████████████████████▍                       | 334/473 [06:26<02:10,  1.07it/s]

fire.654.png








 71%|████████████████████████████████████████████████████████▋                       | 335/473 [06:27<02:17,  1.00it/s]

fire.655.png








 71%|████████████████████████████████████████████████████████▊                       | 336/473 [06:28<02:14,  1.02it/s]

fire.656.png








 71%|████████████████████████████████████████████████████████▉                       | 337/473 [06:29<02:09,  1.05it/s]

fire.657.png








 71%|█████████████████████████████████████████████████████████▏                      | 338/473 [06:30<02:15,  1.00s/it]

fire.658.png








 72%|█████████████████████████████████████████████████████████▎                      | 339/473 [06:31<02:09,  1.03it/s]

fire.659.png








 72%|█████████████████████████████████████████████████████████▌                      | 340/473 [06:31<02:05,  1.06it/s]

fire.66.png








 72%|█████████████████████████████████████████████████████████▋                      | 341/473 [06:32<02:02,  1.08it/s]

fire.660.png








 72%|█████████████████████████████████████████████████████████▊                      | 342/473 [06:33<01:59,  1.10it/s]

fire.661.png








 73%|██████████████████████████████████████████████████████████                      | 343/473 [06:34<01:58,  1.10it/s]

fire.662.png








 73%|██████████████████████████████████████████████████████████▏                     | 344/473 [06:35<01:57,  1.10it/s]

fire.663.png








 73%|██████████████████████████████████████████████████████████▎                     | 345/473 [06:36<01:56,  1.10it/s]

fire.664.png








 73%|██████████████████████████████████████████████████████████▌                     | 346/473 [06:40<03:59,  1.89s/it]

fire.665.png








 73%|██████████████████████████████████████████████████████████▋                     | 347/473 [06:41<03:19,  1.59s/it]

fire.666.png








 74%|██████████████████████████████████████████████████████████▊                     | 348/473 [06:42<02:51,  1.37s/it]

fire.667.png








 74%|███████████████████████████████████████████████████████████                     | 349/473 [06:45<03:52,  1.87s/it]

fire.668.png








 74%|███████████████████████████████████████████████████████████▏                    | 350/473 [06:46<03:14,  1.58s/it]

fire.669.png








 74%|███████████████████████████████████████████████████████████▎                    | 351/473 [06:47<02:48,  1.38s/it]

fire.67.png








 74%|███████████████████████████████████████████████████████████▌                    | 352/473 [06:48<02:30,  1.24s/it]

fire.670.png








 75%|███████████████████████████████████████████████████████████▋                    | 353/473 [06:49<02:16,  1.14s/it]

fire.671.png








 75%|███████████████████████████████████████████████████████████▊                    | 354/473 [06:49<02:07,  1.07s/it]

fire.672.png








 75%|████████████████████████████████████████████████████████████                    | 355/473 [06:50<02:00,  1.02s/it]

fire.673.png








 75%|████████████████████████████████████████████████████████████▏                   | 356/473 [06:51<01:56,  1.01it/s]

fire.674.png








 75%|████████████████████████████████████████████████████████████▍                   | 357/473 [06:52<01:51,  1.04it/s]

fire.675.png








 76%|████████████████████████████████████████████████████████████▌                   | 358/473 [06:53<01:48,  1.06it/s]

fire.676.png








 76%|████████████████████████████████████████████████████████████▋                   | 359/473 [06:54<01:45,  1.08it/s]

fire.677.png








 76%|████████████████████████████████████████████████████████████▉                   | 360/473 [06:55<01:44,  1.08it/s]

fire.678.png








 76%|█████████████████████████████████████████████████████████████                   | 361/473 [06:56<01:44,  1.07it/s]

fire.679.png








 77%|█████████████████████████████████████████████████████████████▏                  | 362/473 [06:57<01:42,  1.08it/s]

fire.68.png








 77%|█████████████████████████████████████████████████████████████▍                  | 363/473 [06:58<01:41,  1.08it/s]

fire.680.png








 77%|█████████████████████████████████████████████████████████████▌                  | 364/473 [06:59<01:41,  1.08it/s]

fire.681.png








 77%|█████████████████████████████████████████████████████████████▋                  | 365/473 [07:00<01:48,  1.00s/it]

fire.682.png








 77%|█████████████████████████████████████████████████████████████▉                  | 366/473 [07:01<01:50,  1.03s/it]

fire.683.png








 78%|██████████████████████████████████████████████████████████████                  | 367/473 [07:02<01:45,  1.00it/s]

fire.684.png








 78%|██████████████████████████████████████████████████████████████▏                 | 368/473 [07:03<01:41,  1.03it/s]

fire.685.png








 78%|██████████████████████████████████████████████████████████████▍                 | 369/473 [07:04<01:38,  1.05it/s]

fire.686.png








 78%|██████████████████████████████████████████████████████████████▌                 | 370/473 [07:04<01:35,  1.07it/s]

fire.687.png








 78%|██████████████████████████████████████████████████████████████▋                 | 371/473 [07:06<01:39,  1.02it/s]

fire.688.png








 79%|██████████████████████████████████████████████████████████████▉                 | 372/473 [07:06<01:36,  1.05it/s]

fire.689.png








 79%|███████████████████████████████████████████████████████████████                 | 373/473 [07:07<01:31,  1.09it/s]

fire.69.png








 79%|███████████████████████████████████████████████████████████████▎                | 374/473 [07:11<02:54,  1.77s/it]

fire.690.png








 79%|███████████████████████████████████████████████████████████████▍                | 375/473 [07:12<02:27,  1.51s/it]

fire.691.png








 79%|███████████████████████████████████████████████████████████████▌                | 376/473 [07:13<02:19,  1.44s/it]

fire.692.png








 80%|███████████████████████████████████████████████████████████████▊                | 377/473 [07:14<02:02,  1.27s/it]

fire.693.png








 80%|███████████████████████████████████████████████████████████████▉                | 378/473 [07:15<01:52,  1.18s/it]

fire.694.png








 80%|████████████████████████████████████████████████████████████████                | 379/473 [07:16<01:43,  1.10s/it]

fire.695.png








 80%|████████████████████████████████████████████████████████████████▎               | 380/473 [07:17<01:36,  1.04s/it]

fire.696.png








 81%|████████████████████████████████████████████████████████████████▍               | 381/473 [07:18<01:30,  1.01it/s]

fire.697.png








 81%|████████████████████████████████████████████████████████████████▌               | 382/473 [07:19<01:33,  1.02s/it]

fire.698.png








 81%|████████████████████████████████████████████████████████████████▊               | 383/473 [07:20<01:28,  1.02it/s]

fire.699.png








 81%|████████████████████████████████████████████████████████████████▉               | 384/473 [07:21<01:25,  1.04it/s]

fire.7.png








 81%|█████████████████████████████████████████████████████████████████               | 385/473 [07:22<01:28,  1.00s/it]

fire.70.png








 82%|█████████████████████████████████████████████████████████████████▎              | 386/473 [07:23<01:21,  1.06it/s]

fire.700.png








 82%|█████████████████████████████████████████████████████████████████▍              | 387/473 [07:23<01:19,  1.09it/s]

fire.701.png








 82%|█████████████████████████████████████████████████████████████████▌              | 388/473 [07:24<01:17,  1.10it/s]

fire.702.png








 82%|█████████████████████████████████████████████████████████████████▊              | 389/473 [07:25<01:16,  1.11it/s]

fire.703.png








 82%|█████████████████████████████████████████████████████████████████▉              | 390/473 [07:26<01:15,  1.10it/s]

fire.704.png








 83%|██████████████████████████████████████████████████████████████████▏             | 391/473 [07:27<01:14,  1.10it/s]

fire.705.png








 83%|██████████████████████████████████████████████████████████████████▎             | 392/473 [07:28<01:21,  1.00s/it]

fire.706.png








 83%|██████████████████████████████████████████████████████████████████▍             | 393/473 [07:29<01:17,  1.03it/s]

fire.707.png








 83%|██████████████████████████████████████████████████████████████████▋             | 394/473 [07:30<01:14,  1.06it/s]

fire.708.png








 84%|██████████████████████████████████████████████████████████████████▊             | 395/473 [07:31<01:15,  1.04it/s]

fire.709.png








 84%|██████████████████████████████████████████████████████████████████▉             | 396/473 [07:32<01:12,  1.06it/s]

fire.71.png








 84%|███████████████████████████████████████████████████████████████████▏            | 397/473 [07:33<01:10,  1.07it/s]

fire.710.png








 84%|███████████████████████████████████████████████████████████████████▎            | 398/473 [07:34<01:09,  1.08it/s]

fire.711.png








 84%|███████████████████████████████████████████████████████████████████▍            | 399/473 [07:35<01:11,  1.03it/s]

fire.712.png








 85%|███████████████████████████████████████████████████████████████████▋            | 400/473 [07:36<01:08,  1.06it/s]

fire.713.png








 85%|███████████████████████████████████████████████████████████████████▊            | 401/473 [07:37<01:06,  1.08it/s]

fire.714.png








 85%|███████████████████████████████████████████████████████████████████▉            | 402/473 [07:37<01:05,  1.09it/s]

fire.715.png








 85%|████████████████████████████████████████████████████████████████████▏           | 403/473 [07:38<01:03,  1.10it/s]

fire.716.png








 85%|████████████████████████████████████████████████████████████████████▎           | 404/473 [07:39<01:02,  1.11it/s]

fire.717.png








 86%|████████████████████████████████████████████████████████████████████▍           | 405/473 [07:40<01:03,  1.08it/s]

fire.718.png








 86%|████████████████████████████████████████████████████████████████████▋           | 406/473 [07:41<01:01,  1.09it/s]

fire.719.png








 86%|████████████████████████████████████████████████████████████████████▊           | 407/473 [07:42<01:05,  1.01it/s]

fire.72.png








 86%|█████████████████████████████████████████████████████████████████████           | 408/473 [07:43<01:02,  1.04it/s]

fire.720.png








 86%|█████████████████████████████████████████████████████████████████████▏          | 409/473 [07:44<01:00,  1.06it/s]

fire.721.png








 87%|█████████████████████████████████████████████████████████████████████▎          | 410/473 [07:45<00:58,  1.08it/s]

fire.722.png








 87%|█████████████████████████████████████████████████████████████████████▌          | 411/473 [07:46<00:57,  1.08it/s]

fire.723.png








 87%|█████████████████████████████████████████████████████████████████████▋          | 412/473 [07:47<00:56,  1.08it/s]

fire.724.png








 87%|█████████████████████████████████████████████████████████████████████▊          | 413/473 [07:48<00:54,  1.10it/s]

fire.725.png








 88%|██████████████████████████████████████████████████████████████████████          | 414/473 [07:49<00:53,  1.10it/s]

fire.726.png








 88%|██████████████████████████████████████████████████████████████████████▏         | 415/473 [07:49<00:52,  1.11it/s]

fire.727.png








 88%|██████████████████████████████████████████████████████████████████████▎         | 416/473 [07:50<00:51,  1.10it/s]

fire.728.png








 88%|██████████████████████████████████████████████████████████████████████▌         | 417/473 [07:51<00:50,  1.10it/s]

fire.729.png








 88%|██████████████████████████████████████████████████████████████████████▋         | 418/473 [07:52<00:49,  1.10it/s]

fire.73.png








 89%|██████████████████████████████████████████████████████████████████████▊         | 419/473 [07:53<00:48,  1.10it/s]

fire.730.png








 89%|███████████████████████████████████████████████████████████████████████         | 420/473 [07:54<00:47,  1.11it/s]

fire.731.png








 89%|███████████████████████████████████████████████████████████████████████▏        | 421/473 [07:55<00:47,  1.10it/s]

fire.732.png








 89%|███████████████████████████████████████████████████████████████████████▎        | 422/473 [07:56<00:49,  1.03it/s]

fire.733.png








 89%|███████████████████████████████████████████████████████████████████████▌        | 423/473 [07:57<00:47,  1.05it/s]

fire.734.png








 90%|███████████████████████████████████████████████████████████████████████▋        | 424/473 [07:58<00:45,  1.09it/s]

fire.735.png








 90%|███████████████████████████████████████████████████████████████████████▉        | 425/473 [07:59<00:43,  1.10it/s]

fire.736.png








 90%|████████████████████████████████████████████████████████████████████████        | 426/473 [08:00<00:43,  1.09it/s]

fire.737.png








 90%|████████████████████████████████████████████████████████████████████████▏       | 427/473 [08:01<00:42,  1.09it/s]

fire.738.png








 90%|████████████████████████████████████████████████████████████████████████▍       | 428/473 [08:01<00:41,  1.09it/s]

fire.739.png








 91%|████████████████████████████████████████████████████████████████████████▌       | 429/473 [08:02<00:41,  1.06it/s]

fire.74.png








 91%|████████████████████████████████████████████████████████████████████████▋       | 430/473 [08:03<00:39,  1.08it/s]

fire.740.png








 91%|████████████████████████████████████████████████████████████████████████▉       | 431/473 [08:04<00:38,  1.09it/s]

fire.741.png








 91%|█████████████████████████████████████████████████████████████████████████       | 432/473 [08:05<00:37,  1.10it/s]

fire.742.png








 92%|█████████████████████████████████████████████████████████████████████████▏      | 433/473 [08:07<00:43,  1.10s/it]

fire.743.png








 92%|█████████████████████████████████████████████████████████████████████████▍      | 434/473 [08:08<00:39,  1.02s/it]

fire.744.png








 92%|█████████████████████████████████████████████████████████████████████████▌      | 435/473 [08:08<00:37,  1.02it/s]

fire.745.png








 92%|█████████████████████████████████████████████████████████████████████████▋      | 436/473 [08:09<00:35,  1.04it/s]

fire.746.png








 92%|█████████████████████████████████████████████████████████████████████████▉      | 437/473 [08:10<00:33,  1.06it/s]

fire.747.png








 93%|██████████████████████████████████████████████████████████████████████████      | 438/473 [08:11<00:32,  1.09it/s]

fire.748.png








 93%|██████████████████████████████████████████████████████████████████████████▏     | 439/473 [08:12<00:31,  1.08it/s]

fire.749.png








 93%|██████████████████████████████████████████████████████████████████████████▍     | 440/473 [08:13<00:30,  1.10it/s]

fire.75.png








 93%|██████████████████████████████████████████████████████████████████████████▌     | 441/473 [08:14<00:28,  1.11it/s]

fire.750.png








 93%|██████████████████████████████████████████████████████████████████████████▊     | 442/473 [08:15<00:27,  1.11it/s]

fire.751.png








 94%|██████████████████████████████████████████████████████████████████████████▉     | 443/473 [08:16<00:26,  1.12it/s]

fire.752.png








 94%|███████████████████████████████████████████████████████████████████████████     | 444/473 [08:16<00:26,  1.11it/s]

fire.753.png








 94%|███████████████████████████████████████████████████████████████████████████▎    | 445/473 [08:17<00:25,  1.09it/s]

fire.754.png








 94%|███████████████████████████████████████████████████████████████████████████▍    | 446/473 [08:18<00:24,  1.11it/s]

fire.755.png








 95%|███████████████████████████████████████████████████████████████████████████▌    | 447/473 [08:19<00:23,  1.11it/s]

fire.76.png








 95%|███████████████████████████████████████████████████████████████████████████▊    | 448/473 [08:20<00:22,  1.11it/s]

fire.77.png








 95%|███████████████████████████████████████████████████████████████████████████▉    | 449/473 [08:21<00:21,  1.10it/s]

fire.78.png








 95%|████████████████████████████████████████████████████████████████████████████    | 450/473 [08:22<00:20,  1.13it/s]

fire.79.png








 95%|████████████████████████████████████████████████████████████████████████████▎   | 451/473 [08:23<00:19,  1.13it/s]

fire.8.png








 96%|████████████████████████████████████████████████████████████████████████████▍   | 452/473 [08:24<00:19,  1.07it/s]

fire.80.png








 96%|████████████████████████████████████████████████████████████████████████████▌   | 453/473 [08:25<00:18,  1.08it/s]

fire.81.png








 96%|████████████████████████████████████████████████████████████████████████████▊   | 454/473 [08:26<00:17,  1.10it/s]

fire.82.png








 96%|████████████████████████████████████████████████████████████████████████████▉   | 455/473 [08:26<00:16,  1.11it/s]

fire.83.png








 96%|█████████████████████████████████████████████████████████████████████████████   | 456/473 [08:27<00:15,  1.12it/s]

fire.84.png








 97%|█████████████████████████████████████████████████████████████████████████████▎  | 457/473 [08:28<00:14,  1.11it/s]

fire.85.png








 97%|█████████████████████████████████████████████████████████████████████████████▍  | 458/473 [08:29<00:13,  1.14it/s]

fire.86.png








 97%|█████████████████████████████████████████████████████████████████████████████▋  | 459/473 [08:30<00:12,  1.14it/s]

fire.87.png








 97%|█████████████████████████████████████████████████████████████████████████████▊  | 460/473 [08:31<00:11,  1.15it/s]

fire.88.png








 97%|█████████████████████████████████████████████████████████████████████████████▉  | 461/473 [08:32<00:10,  1.14it/s]

fire.89.png








 98%|██████████████████████████████████████████████████████████████████████████████▏ | 462/473 [08:33<00:10,  1.05it/s]

fire.9.png








 98%|██████████████████████████████████████████████████████████████████████████████▎ | 463/473 [08:34<00:09,  1.06it/s]

fire.90.png








 98%|██████████████████████████████████████████████████████████████████████████████▍ | 464/473 [08:35<00:08,  1.09it/s]

fire.91.png








 98%|██████████████████████████████████████████████████████████████████████████████▋ | 465/473 [08:36<00:07,  1.02it/s]

fire.92.png








 99%|██████████████████████████████████████████████████████████████████████████████▊ | 466/473 [08:37<00:06,  1.05it/s]

fire.93.png








 99%|██████████████████████████████████████████████████████████████████████████████▉ | 467/473 [08:38<00:05,  1.06it/s]

fire.94.png








 99%|███████████████████████████████████████████████████████████████████████████████▏| 468/473 [08:39<00:04,  1.02it/s]

fire.95.png








 99%|███████████████████████████████████████████████████████████████████████████████▎| 469/473 [08:39<00:03,  1.05it/s]

fire.96.png








 99%|███████████████████████████████████████████████████████████████████████████████▍| 470/473 [08:40<00:02,  1.07it/s]

fire.97.png








100%|███████████████████████████████████████████████████████████████████████████████▋| 471/473 [08:43<00:02,  1.34s/it]

fire.98.png








100%|███████████████████████████████████████████████████████████████████████████████▊| 472/473 [08:43<00:01,  1.19s/it]

fire.99.png








100%|████████████████████████████████████████████████████████████████████████████████| 473/473 [08:44<00:00,  1.11s/it]


In [122]:
TEST_SIZE = 400

train_gray = gray_img[:TEST_SIZE]
train_color = color_img[:TEST_SIZE]
test_gray = gray_img[TEST_SIZE:]
test_color = color_img[TEST_SIZE:]

train_g = np.reshape(train_gray, (len(train_gray), SIZE, SIZE, 3))
train_c = np.reshape(train_color, (len(train_color), SIZE, SIZE, 3))
test_g = np.reshape(test_gray, (len(test_gray), SIZE, SIZE, 3))
test_c = np.reshape(test_color, (len(test_color), SIZE, SIZE, 3))

In [166]:
# Create and compile model
model = Autoencoder()
model.compile(optimizer=Adam(),
              loss='mean_squared_error',
              metrics=['accuracy'])
model.fit(train_g, train_c, batch_size=32, epochs=1, validation_data=(test_g, test_c))

# y = model(test_g[23:22])
# plot_images(y, test_g[23])

Train on 400 samples, validate on 73 samples
 32/400 [=>............................] - ETA: 0s

ValueError: Dimensions must be equal, but are 112 and 224 for 'loss/output_1_loss/SquaredDifference' (op: 'SquaredDifference') with input shapes: [?,112,112,224], [?,224,224,3].

In [169]:
model.summary()

Model: "autoencoder"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
encoder (Encoder)            multiple                  900739    
_________________________________________________________________
decoder (Decoder)            multiple                  754375    
Total params: 1,655,114
Trainable params: 1,655,114
Non-trainable params: 0
_________________________________________________________________


In [170]:
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

# Load data
(y_train, _), (y_test, _) = cifar100.load_data()
y_train = y_train.astype('float32') / 255.
y_test = y_test.astype('float32') / 255.
x_train = tf.expand_dims(rgb2lab(y_train)[:, :, :, 0], axis=-1)
y_train = rgb2lab(y_train)[:, :, :, 1:] / 128.
x_test = tf.expand_dims(rgb2lab(y_test)[:, :, :, 0], axis=-1)
y_test = rgb2lab(y_test)[:, :, :, 1:] / 128.

# Print shapes of datasets
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

# Create, compile and train model
model = Autoencoder()
model.compile(optimizer=Adam(),
              loss='mean_squared_error',
              metrics=['accuracy'])
model.fit(x_train, y_train, batch_size=32, epochs=1, validation_data=(x_test, y_test))
# model.save("autoencoder_cielab_imagenet")
# model = tf.keras.models.load_model("autoencoder_cielab")

for i in range(1):
    # Test model on examplary input
    y = model(x_test[i:i+1])

    # Plot examplary gray and colored image
    plt.subplot(131)
    plt.imshow(tf.squeeze(x_test[i]), cmap='gray')
    plt.title("Gray image")
    plt.subplot(132)
    img = np.zeros((32, 32, 3))
    img[:, :, 0] = tf.squeeze(x_test[i])
    img[:, :, 1:] = tf.squeeze(y * 128)
    plt.imshow(lab2rgb(img))
    plt.title("Colorized image")
    plt.subplot(133)
    img[:, :, 1:] = tf.squeeze(y_test[i] * 128)
    plt.imshow(lab2rgb(img))
    plt.title("Original image")
    plt.show()

Num GPUs Available:  0
(50000, 32, 32, 1)
(50000, 32, 32, 2)
(10000, 32, 32, 1)
(10000, 32, 32, 2)


ValueError: Do not pass inputs that mix Numpy arrays and TensorFlow tensors. You passed: x=tf.Tensor(
[[[[100.        ]
   [100.        ]
   [100.        ]
   ...
   [ 81.35465005]
   [ 87.8084554 ]
   [ 76.87163082]]

  [[100.        ]
   [ 99.65492696]
   [ 99.65492696]
   ...
   [ 70.73205133]
   [ 67.42256133]
   [ 62.01039024]]

  [[100.        ]
   [ 99.65492696]
   [100.        ]
   ...
   [ 78.76996893]
   [ 70.56630578]
   [ 53.52285432]]

  ...

  [[ 70.56528724]
   [ 69.11336065]
   [ 68.12500748]
   ...
   [  6.13495266]
   [ 25.5745673 ]
   [ 31.56656946]]

  [[ 60.46679828]
   [ 59.65415106]
   [ 61.68186611]
   ...
   [  4.9478991 ]
   [ 44.82277102]
   [ 63.21105292]]

  [[ 47.11224251]
   [ 47.15777185]
   [ 51.95264789]
   ...
   [ 13.37427905]
   [ 51.9433427 ]
   [ 66.40885115]]]


 [[[100.        ]
   [ 99.30958769]
   [ 99.30958769]
   ...
   [ 99.30958769]
   [ 99.30958769]
   [100.        ]]

  [[100.        ]
   [100.        ]
   [100.        ]
   ...
   [100.        ]
   [100.        ]
   [100.        ]]

  [[100.        ]
   [100.        ]
   [100.        ]
   ...
   [100.        ]
   [100.        ]
   [100.        ]]

  ...

  [[100.        ]
   [100.        ]
   [100.        ]
   ...
   [100.        ]
   [100.        ]
   [100.        ]]

  [[100.        ]
   [100.        ]
   [100.        ]
   ...
   [100.        ]
   [100.        ]
   [100.        ]]

  [[100.        ]
   [ 99.30958769]
   [ 99.30958769]
   ...
   [ 99.30958769]
   [ 99.30958769]
   [100.        ]]]


 [[[ 98.22229635]
   [ 97.70406703]
   [ 97.28485173]
   ...
   [ 98.17304901]
   [ 98.17304901]
   [ 98.09943182]]

  [[ 98.39687839]
   [ 97.58405777]
   [ 96.91690861]
   ...
   [ 98.39831211]
   [ 98.67065725]
   [ 98.34856975]]

  [[ 98.44631751]
   [ 97.45992806]
   [ 96.62072398]
   ...
   [ 97.73213735]
   [ 97.77965165]
   [ 97.82765212]]

  ...

  [[ 85.36392048]
   [ 83.25824437]
   [ 83.95057358]
   ...
   [ 72.83628488]
   [ 78.53344493]
   [ 91.16798891]]

  [[ 88.5159066 ]
   [ 87.47547268]
   [ 86.96787779]
   ...
   [ 75.9285179 ]
   [ 81.32816472]
   [ 92.04587695]]

  [[ 92.17289572]
   [ 91.94794802]
   [ 91.54668882]
   ...
   [ 84.25486304]
   [ 86.65499456]
   [ 91.39288961]]]


 ...


 [[[ 96.43842453]
   [ 92.38336124]
   [ 92.075708  ]
   ...
   [ 91.06960703]
   [ 90.58972848]
   [ 93.7229578 ]]

  [[ 85.9846935 ]
   [ 69.64543419]
   [ 66.37030178]
   ...
   [ 62.24357921]
   [ 60.52342577]
   [ 75.21588616]]

  [[ 79.26798352]
   [ 52.05060223]
   [ 50.02478225]
   ...
   [ 38.39767947]
   [ 39.72459801]
   [ 60.93021084]]

  ...

  [[ 65.4936012 ]
   [ 13.58675735]
   [  7.03605868]
   ...
   [ 32.30110539]
   [ 29.8527601 ]
   [ 53.37818051]]

  [[ 72.92001382]
   [ 35.40183409]
   [ 28.95811148]
   ...
   [ 45.02537973]
   [ 40.02667696]
   [ 60.56340728]]

  [[ 88.7732933 ]
   [ 73.18136375]
   [ 70.30145301]
   ...
   [ 76.41915547]
   [ 72.86840481]
   [ 82.32912461]]]


 [[[ 63.33094863]
   [ 60.39808217]
   [ 59.89501405]
   ...
   [ 61.96931043]
   [ 61.07728134]
   [ 74.42255129]]

  [[ 44.46036682]
   [ 45.34026791]
   [ 43.03429935]
   ...
   [ 44.74275478]
   [ 43.30960882]
   [ 53.53769078]]

  [[ 46.85733888]
   [ 49.05140477]
   [ 49.43776733]
   ...
   [ 36.30608937]
   [ 37.40451174]
   [ 49.85368317]]

  ...

  [[ 42.84350185]
   [ 42.49982733]
   [ 44.6644785 ]
   ...
   [ 47.78809354]
   [ 47.16040041]
   [ 52.44292655]]

  [[ 38.91591544]
   [ 34.97016047]
   [ 35.62305056]
   ...
   [ 41.24204318]
   [ 39.74092254]
   [ 48.13640209]]

  [[ 68.18850708]
   [ 62.98148679]
   [ 62.9906345 ]
   ...
   [ 62.44508581]
   [ 59.95803155]
   [ 63.67600953]]]


 [[[ 28.66877294]
   [ 29.06860808]
   [ 29.54609001]
   ...
   [ 30.08748272]
   [ 29.83064823]
   [ 29.33088303]]

  [[ 29.16136738]
   [ 29.56536397]
   [ 29.77073868]
   ...
   [ 30.21862875]
   [ 29.65046935]
   [ 29.41756185]]

  [[ 28.89160706]
   [ 29.29397034]
   [ 29.77073868]
   ...
   [ 30.89466302]
   [ 30.11426522]
   [ 29.57277231]]

  ...

  [[ 18.09337998]
   [ 18.31916793]
   [ 19.0698247 ]
   ...
   [ 19.21190205]
   [ 18.38096023]
   [ 18.09337998]]

  [[ 17.38126318]
   [ 17.65965639]
   [ 18.09337998]
   ...
   [ 18.09337998]
   [ 18.05936836]
   [ 17.38126318]]

  [[ 17.19898098]
   [ 17.25896806]
   [ 17.31973028]
   ...
   [ 17.1098591 ]
   [ 16.73404868]
   [ 16.40189769]]]], shape=(50000, 32, 32, 1), dtype=float64); y=[[[[-1.91792020e-05  3.63548528e-05]
   [-1.91792020e-05  3.63548528e-05]
   [-1.91792020e-05  3.63548528e-05]
   ...
   [-4.38911154e-02  3.74660357e-02]
   [-5.94153716e-02  6.57547067e-02]
   [-7.03948103e-02  9.53073729e-02]]

  [[-1.91792020e-05  3.63548528e-05]
   [-1.91221484e-05  3.62467055e-05]
   [-1.91221484e-05  3.62467055e-05]
   ...
   [-5.29482030e-02  9.86098148e-02]
   [-7.12667301e-02  1.47305102e-01]
   [-7.86117132e-02  1.61129550e-01]]

  [[-1.91792020e-05  3.63548528e-05]
   [-1.91221484e-05  3.62467055e-05]
   [-1.91792020e-05  3.63548528e-05]
   ...
   [-6.83605276e-02  1.08439310e-01]
   [-9.73377142e-02  1.81301595e-01]
   [-9.82337623e-02  1.82739512e-01]]

  ...

  [[-2.26972404e-01  3.81446588e-01]
   [-2.47889475e-01  4.41815899e-01]
   [-2.41437352e-01  4.24125083e-01]
   ...
   [ 3.06798918e-02  6.91428470e-02]
   [-4.25235386e-02  2.19151836e-01]
   [-6.73719416e-02  2.51029821e-01]]

  [[-2.11008429e-01  3.35238119e-01]
   [-2.15317868e-01  3.56789157e-01]
   [-2.06210830e-01  3.28006043e-01]
   ...
   [ 3.83920380e-03  4.83436597e-02]
   [-1.19645967e-01  2.27331307e-01]
   [-1.49675860e-01  2.81730334e-01]]

  [[-2.05071930e-01  3.05485107e-01]
   [-2.03208517e-01  3.13066957e-01]
   [-1.95991179e-01  2.93845710e-01]
   ...
   [-4.42459976e-02  1.20965845e-01]
   [-1.76892722e-01  2.82620383e-01]
   [-2.12449048e-01  3.42581868e-01]]]


 [[[-1.91792020e-05  3.63548528e-05]
   [-1.90650507e-05  3.61384749e-05]
   [-1.90650507e-05  3.61384749e-05]
   ...
   [-1.90650507e-05  3.61384749e-05]
   [-1.90650507e-05  3.61384749e-05]
   [-1.91792020e-05  3.63548528e-05]]

  [[-1.91792020e-05  3.63548528e-05]
   [-1.91792020e-05  3.63548528e-05]
   [-1.91792020e-05  3.63548528e-05]
   ...
   [-1.91792020e-05  3.63548528e-05]
   [-1.91792020e-05  3.63548528e-05]
   [-1.91792020e-05  3.63548528e-05]]

  [[-1.91792020e-05  3.63548528e-05]
   [-1.91792020e-05  3.63548528e-05]
   [-1.91792020e-05  3.63548528e-05]
   ...
   [-1.91792020e-05  3.63548528e-05]
   [-1.91792020e-05  3.63548528e-05]
   [-1.91792020e-05  3.63548528e-05]]

  ...

  [[-1.91792020e-05  3.63548528e-05]
   [-1.91792020e-05  3.63548528e-05]
   [-1.91792020e-05  3.63548528e-05]
   ...
   [-1.91792020e-05  3.63548528e-05]
   [-1.91792020e-05  3.63548528e-05]
   [-1.91792020e-05  3.63548528e-05]]

  [[-1.91792020e-05  3.63548528e-05]
   [-1.91792020e-05  3.63548528e-05]
   [-1.91792020e-05  3.63548528e-05]
   ...
   [-1.91792020e-05  3.63548528e-05]
   [-1.91792020e-05  3.63548528e-05]
   [-1.91792020e-05  3.63548528e-05]]

  [[-1.91792020e-05  3.63548528e-05]
   [-1.90650507e-05  3.61384749e-05]
   [-1.90650507e-05  3.61384749e-05]
   ...
   [-1.90650507e-05  3.61384749e-05]
   [-1.90650507e-05  3.61384749e-05]
   [-1.91792020e-05  3.63548528e-05]]]


 [[[-2.75238517e-03  7.50651231e-03]
   [-1.07720249e-02  2.15752744e-02]
   [-1.47988102e-02  3.28438416e-02]
   ...
   [-5.46535793e-03  1.49833277e-02]
   [-5.46535793e-03  1.49833277e-02]
   [-8.06253349e-03  1.40760974e-02]]

  [[-1.07563622e-02  2.15426566e-02]
   [-1.74392195e-02  4.03210954e-02]
   [-1.74508900e-02  4.88110786e-02]
   ...
   [-1.21488527e-02  3.36751741e-02]
   [-1.47569069e-02  3.27441324e-02]
   [-1.34354686e-02  2.90254199e-02]]

  [[-9.48941853e-03  2.61897042e-02]
   [-9.53854254e-03  4.30875725e-02]
   [-2.88412998e-03  4.97261427e-02]
   ...
   [-1.21717836e-02  4.21398189e-02]
   [-9.53933500e-03  3.46376550e-02]
   [-6.88586966e-03  2.71408376e-02]]

  ...

  [[-7.24196727e-03  9.26936022e-02]
   [ 3.33168153e-03  1.31447719e-01]
   [ 1.65529999e-02  1.18746014e-01]
   ...
   [ 1.60540459e-02  1.92084931e-01]
   [ 3.10368034e-03  1.24182289e-01]
   [ 6.40911325e-03  1.51578622e-02]]

  [[-2.01004027e-02  7.46691834e-02]
   [-8.49845242e-03  9.60597698e-02]
   [ 1.41279019e-02  7.41371381e-02]
   ...
   [ 1.15326575e-02  1.54264467e-01]
   [ 2.60679845e-03  9.27668633e-02]
   [-2.56600199e-04  1.70463775e-02]]

  [[-9.61323920e-03  2.65609264e-02]
   [-5.64690887e-03  3.22325730e-02]
   [ 6.36577965e-03  2.36854802e-02]
   ...
   [ 7.14613723e-03  6.77623156e-02]
   [ 6.54626989e-03  4.12871765e-02]
   [ 2.47674219e-03  9.47792000e-03]]]


 ...


 [[[ 7.67069824e-03  1.12223791e-02]
   [ 9.10293145e-03  4.16775488e-02]
   [-1.63300809e-03  3.78992025e-02]
   ...
   [ 1.02596957e-03  3.03752576e-02]
   [-2.96967087e-03  2.47173875e-02]
   [-2.88958071e-03  1.60543306e-02]]

  [[ 2.02983726e-02  4.62786252e-02]
   [ 3.08003325e-02  9.23980092e-02]
   [ 2.10156319e-02  9.41256891e-02]
   ...
   [ 2.47139111e-02  7.36042191e-02]
   [ 1.96848769e-02  5.82297581e-02]
   [ 1.10256001e-02  3.95931612e-02]]

  [[ 2.16059089e-02  7.37849360e-02]
   [ 4.27649537e-02  1.34586822e-01]
   [ 4.03932014e-02  1.48646053e-01]
   ...
   [ 5.12533065e-02  1.14685663e-01]
   [ 4.24103113e-02  8.59214028e-02]
   [ 2.09666366e-02  5.39976507e-02]]

  ...

  [[-3.09667297e-03  2.64385559e-02]
   [ 8.60660117e-03  3.83831420e-02]
   [ 2.17523813e-02  3.63183832e-02]
   ...
   [ 4.70296178e-02  1.15763799e-01]
   [ 3.92387157e-02  1.03653410e-01]
   [ 1.42285555e-02  5.75031690e-02]]

  [[-4.45557016e-03  2.98527682e-02]
   [ 2.87617951e-05  3.08515038e-02]
   [ 1.50336394e-04  3.19253787e-02]
   ...
   [ 4.07998154e-02  8.37272955e-02]
   [ 2.70194385e-02  6.00457539e-02]
   [ 1.14385877e-02  2.27267713e-02]]

  [[-4.28816022e-03  2.00615782e-02]
   [-7.21706047e-03  1.99108487e-02]
   [-4.46778899e-03  2.10567327e-02]
   ...
   [ 1.51316841e-02  3.65150334e-02]
   [ 8.14551722e-03  2.08710433e-02]
   [-2.69230737e-03 -9.10599987e-04]]]


 [[[-1.83107767e-02  7.18301632e-02]
   [-1.70585593e-02  1.00601082e-01]
   [-5.86447492e-03  8.62438855e-02]
   ...
   [-1.45382862e-02  9.18083715e-02]
   [-2.01162187e-02  9.93215281e-02]
   [-2.31497006e-02  8.54195340e-02]]

  [[-2.72888335e-02  1.31961888e-01]
   [-3.07961975e-02  2.09299159e-01]
   [-1.04183860e-02  2.08481219e-01]
   ...
   [-2.26451258e-02  2.07846519e-01]
   [-3.10909939e-02  2.15004114e-01]
   [-3.33145017e-02  1.62423450e-01]]

  [[-2.85270650e-02  1.35042632e-01]
   [-4.39161953e-02  2.29362088e-01]
   [-2.91751855e-02  2.29463768e-01]
   ...
   [ 2.56905911e-03  2.03361382e-01]
   [-4.09959799e-03  2.14022853e-01]
   [-7.62248517e-03  1.50031703e-01]]

  ...

  [[-1.12649004e-02  1.28673458e-01]
   [-1.54863631e-02  2.16133798e-01]
   [-1.01710258e-02  2.03002961e-01]
   ...
   [-1.55509156e-02  2.21727252e-01]
   [-9.80662732e-03  2.32902217e-01]
   [-1.21771236e-03  1.64822211e-01]]

  [[-1.99709054e-02  1.37453979e-01]
   [-1.63430802e-02  2.24572350e-01]
   [-7.63246873e-03  2.18295709e-01]
   ...
   [-2.40466820e-03  2.34502966e-01]
   [ 3.66477245e-03  2.28608312e-01]
   [ 1.82508930e-03  1.58912362e-01]]

  [[-2.17139133e-02  9.20465632e-02]
   [-2.51490974e-02  1.51307178e-01]
   [-1.03682724e-02  1.47399265e-01]
   ...
   [-1.78668130e-02  1.63041539e-01]
   [-1.11881164e-02  1.66582488e-01]
   [-1.09131629e-02  1.24350325e-01]]]


 [[[ 5.83440456e-02 -2.74340360e-01]
   [ 5.80805163e-02 -2.79151678e-01]
   [ 6.01779572e-02 -2.82929522e-01]
   ...
   [ 6.53868950e-02 -2.90740134e-01]
   [ 5.29314311e-02 -2.74480600e-01]
   [ 4.89169801e-02 -2.66056793e-01]]

  [[ 6.32495375e-02 -2.87776289e-01]
   [ 6.31521049e-02 -2.92478952e-01]
   [ 7.16060312e-02 -2.99597044e-01]
   ...
   [ 7.16265571e-02 -2.98803352e-01]
   [ 6.44769834e-02 -2.86479878e-01]
   [ 5.39248880e-02 -2.74774212e-01]]

  [[ 6.97271893e-02 -2.91138720e-01]
   [ 6.95683356e-02 -2.95863914e-01]
   [ 7.16060312e-02 -2.99597044e-01]
   ...
   [ 6.41203685e-02 -2.95181529e-01]
   [ 6.73721227e-02 -2.95276769e-01]
   [ 6.21691144e-02 -2.87485847e-01]]

  ...

  [[ 7.72417641e-02 -1.71763723e-01]
   [ 6.93108712e-02 -1.69013306e-01]
   [ 6.36809145e-02 -1.70302595e-01]
   ...
   [ 6.87361241e-02 -1.73771885e-01]
   [ 7.20908494e-02 -1.73542103e-01]
   [ 7.72417641e-02 -1.71763723e-01]]

  [[ 8.27187619e-02 -1.64571206e-01]
   [ 7.73940673e-02 -1.66504529e-01]
   [ 7.72417641e-02 -1.71763723e-01]
   ...
   [ 7.72417641e-02 -1.71763723e-01]
   [ 7.41861621e-02 -1.61520782e-01]
   [ 8.27187619e-02 -1.64571206e-01]]

  [[ 7.47614345e-02 -1.50775330e-01]
   [ 7.73996858e-02 -1.55392518e-01]
   [ 8.00523267e-02 -1.59991135e-01]
   ...
   [ 8.81285578e-02 -1.62535771e-01]
   [ 7.52253287e-02 -1.51185074e-01]
   [ 7.81820570e-02 -1.44450763e-01]]]]